name: flutter_classes
description: Collection of Flutter classes used by almost ever app.
version: 0.0.1+4
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.0" #Dart SDK 4-SEP-2021
  flutter: ">=2.5.0"

dependencies:
  app_exception:
    git:
      url: https://github.com/GitHubStuff/app_exception.git
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_modular: ^4.0.0+7
  intl: ^0.17.0

dev_dependencies:
  test: ^1.17.12

flutter:
  uses-material-design: true
